[package]
name = "im-switch"
version = "0.1.0"
authors = ["Junfeng Li <autozimu@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.*"
logger = "0.*"
structopt = "0.*"
structopt-derive = "0.*"

core-foundation-sys = "0.*"
cocoa = "0.*"
