[package]
name = "im-switch"
version = "0.1.0"
authors = ["Junfeng Li <autozimu@gmail.com>"]
edition = "2018"

[dependencies]
failure = "*"
logger = "*"
structopt = "*"
structopt-derive = "*"

core-foundation-sys = "*"
cocoa = "*"
