[package]
name = "im"
version = "0.1.0"
authors = ["Junfeng Li <autozimu@gmail.com>"]
edition = "2021"

[dependencies]
core-foundation = "*"

[lib]
name = "im"
path = "src/im.rs"

[[bin]]
name = "im-switch"
path = "src/main.rs"
